version: "3.8"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: secret